# MQTT bridge to EC2 cloud broker
connection sb-ec2-bridge
address 98.83.4.87:1883

remote_username bridge
remote_password bridge123
remote_clientid sb-bridge-gw-ubuntu-01

topic sb/v1/# both 1

cleansession false
try_private true
restart_timeout 5 30
notifications true
notification_topic sb/v1/hust/lab01/gw-ubuntu-01/bridge/status
