#ifndef APP_ZCL_FALLBACK_H
#define APP_ZCL_FALLBACK_H

// These are ZCL IDs (macros). Safe to fallback with #ifndef
#ifndef ZCL_POWER_CONFIGURATION_CLUSTER_ID
#define ZCL_POWER_CONFIGURATION_CLUSTER_ID 0x0001u
#endif

#ifndef ZCL_BATTERY_PERCENTAGE_REMAINING_ATTRIBUTE_ID
#define ZCL_BATTERY_PERCENTAGE_REMAINING_ATTRIBUTE_ID 0x0021u
#endif

#ifndef ZCL_FLOW_MEASUREMENT_CLUSTER_ID
#define ZCL_FLOW_MEASUREMENT_CLUSTER_ID 0x0404u
#endif

#ifndef ZCL_REPORT_ATTRIBUTES_COMMAND_ID
#define ZCL_REPORT_ATTRIBUTES_COMMAND_ID 0x0Au
#endif

#endif // APP_ZCL_FALLBACK_H
